`timescale 1ns / 1ps

// ============================================================================
// Module      : tb_vrm_windowing_core
// Description : Testbench for the AXI4-Stream Windowing Core
//
// Verification Scope:
//   - AXI4-Stream input/output handshake
//   - Window coefficient ROM loading
//   - Q1.15 sample multiplication
//   - TLAST propagation
//   - Two-channel complex/audio sample processing
//
// Notes:
//   - A dummy ROM file is generated automatically for simulation.
//   - The dummy ROM contains a simple triangular window profile.
//   - The testbench sends a constant input frame so that the output follows
//     the shape of the loaded window coefficients.
// ============================================================================

module tb_vrm_windowing_core;

    // ------------------------------------------------------------------------
    // Parameters and Internal Signals
    // ------------------------------------------------------------------------
    parameter C_AXIS_TDATA_WIDTH = 32;
    parameter MAX_PTS             = 2048;
    parameter ROM_FILE            = "window_2048.mem";

    reg aclk;
    reg aresetn;

    // ------------------------------------------------------------------------
    // AXI4-Stream Slave Interface (Input)
    // ------------------------------------------------------------------------
    reg  [C_AXIS_TDATA_WIDTH-1:0] s_axis_tdata;
    reg                           s_axis_tlast;
    reg                           s_axis_tvalid;
    wire                          s_axis_tready;

    // ------------------------------------------------------------------------
    // AXI4-Stream Master Interface (Output)
    // ------------------------------------------------------------------------
    wire [C_AXIS_TDATA_WIDTH-1:0] m_axis_tdata;
    wire                          m_axis_tlast;
    wire                          m_axis_tvalid;
    reg                           m_axis_tready;

    // ------------------------------------------------------------------------
    // Generate Dummy ROM File for Simulation
    //
    // This ensures that the simulation can run even when the actual ROM
    // initialization file has not yet been generated by the Python utility.
    //
    // The generated ROM contains a simple triangular profile with a maximum
    // coefficient of 32767 (0x7FFF) at the center of the frame.
    // ------------------------------------------------------------------------
    integer file, i;

    initial begin
        file = $fopen(ROM_FILE, "w");

        for (i = 0; i < MAX_PTS; i = i + 1) begin
            if (i < MAX_PTS / 2)
                $fdisplay(
                    file,
                    "%04X",
                    (i * 32767) / (MAX_PTS / 2)
                );
            else
                $fdisplay(
                    file,
                    "%04X",
                    ((MAX_PTS - 1 - i) * 32767) / (MAX_PTS / 2)
                );
        end

        $fclose(file);
    end

    // ------------------------------------------------------------------------
    // Device Under Test (DUT)
    // ------------------------------------------------------------------------
    vrm_windowing_core #(
        .C_AXIS_TDATA_WIDTH(C_AXIS_TDATA_WIDTH),
        .MAX_PTS(MAX_PTS),
        .ROM_FILE(ROM_FILE)
    ) dut (
        .aclk          (aclk),
        .aresetn       (aresetn),

        .s_axis_tdata  (s_axis_tdata),
        .s_axis_tlast  (s_axis_tlast),
        .s_axis_tvalid (s_axis_tvalid),
        .s_axis_tready (s_axis_tready),

        .m_axis_tdata  (m_axis_tdata),
        .m_axis_tlast  (m_axis_tlast),
        .m_axis_tvalid (m_axis_tvalid),
        .m_axis_tready (m_axis_tready)
    );

    // ------------------------------------------------------------------------
    // Clock Generation
    //
    // 100 MHz clock, 10 ns period.
    // ------------------------------------------------------------------------
    initial begin
        aclk = 1'b0;
        forever #5 aclk = ~aclk;
    end

    // ------------------------------------------------------------------------
    // Task: Send One AXI4-Stream Sample
    //
    // The stimulus is driven on the falling edge to provide stable input
    // signals before the following rising-edge handshake.
    // ------------------------------------------------------------------------
    task axis_push_data;
        input signed [15:0] data_l;
        input signed [15:0] data_r;
        input               is_last;

        begin
            @(negedge aclk);

            // Packed format:
            //   [31:16] = Right / Imaginary component
            //   [15:0]  = Left / Real component
            s_axis_tdata  <= {data_r, data_l};
            s_axis_tvalid <= 1'b1;
            s_axis_tlast  <= is_last;

            @(posedge aclk);

            // Wait until the DUT accepts the current sample.
            while (s_axis_tready == 1'b0) begin
                @(posedge aclk);
            end

            @(negedge aclk);

            s_axis_tvalid <= 1'b0;
            s_axis_tlast  <= 1'b0;
        end
    endtask

    // ------------------------------------------------------------------------
    // Main Stimulus
    // ------------------------------------------------------------------------
    integer n;

    initial begin
        // Initialize testbench signals.
        aresetn       = 1'b0;
        s_axis_tdata  = 32'h0;
        s_axis_tlast  = 1'b0;
        s_axis_tvalid = 1'b0;
        m_axis_tready = 1'b1;

        // Apply reset.
        #100;
        aresetn = 1'b1;
        #100;

        $display(
            "[%0t] Starting injection of %0d samples...",
            $time,
            MAX_PTS
        );

        // Send one complete frame.
        //
        // A constant DC input of 10000 is used for both channels.
        // Therefore, the output envelope should follow the shape of the
        // window coefficient stored in the ROM.
        for (n = 0; n < MAX_PTS; n = n + 1) begin
            if (n == MAX_PTS - 1)
                axis_push_data(
                    16'sd10000,
                    16'sd10000,
                    1'b1
                );
            else
                axis_push_data(
                    16'sd10000,
                    16'sd10000,
                    1'b0
                );

            // Optional backpressure test:
            // Uncomment the following line to insert a one-cycle delay
            // between consecutive input transactions.
            // #10;
        end

        $display(
            "[%0t] Input frame completed. Waiting for pipeline to drain...",
            $time
        );

        #200;

        $display("[%0t] Simulation completed.", $time);
        $finish;
    end

    // ------------------------------------------------------------------------
    // Output Monitor
    //
    // Prints every successfully transferred output sample to the simulator
    // console. This monitor can be disabled if waveform-only verification
    // is preferred.
    // ------------------------------------------------------------------------
    always @(posedge aclk) begin
        if (m_axis_tvalid && m_axis_tready) begin
            $display(
                "Output L: %d | R: %d | TLAST: %b",
                $signed(m_axis_tdata[15:0]),
                $signed(m_axis_tdata[31:16]),
                m_axis_tlast
            );
        end
    end

endmodule
